apiVersion: v1
kind: Service
metadata:
  name: {{ template "obyte-devnet.fullname" . }}-witness
  labels:
    app: {{ template "obyte-devnet.name" . }}
    chart: {{ template "obyte-devnet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: witness
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 6612
    targetPort: 6612
  - name: explorer
    port: 8080
    targetPort: 8080
  selector:
    app: {{ template "obyte-devnet.name" . }}
    release: {{ .Release.Name }}
    component: witness
  {{- with .Values.service.externalIPs }}
  externalIPs:
{{ toYaml . | indent 2 }}
  {{- end }}
